### ISSUE TITLE
Actividad 8 Reconocimiento por GPS

### ISSUE THREAD

**Issue by FedericoVictorianoSierra** [SistemasTecTlaxiaco/actividad-8-reconocimeinto-gps-promastergamer#1]

**Comment by FedericoVictorianoSierra** [comment]
[Actividad 8 Reconocimiento GPS.pdf](https://github.com/SistemasTecTlaxiaco/actividad-8-reconocimeinto-gps-promastergamer/files/15169798/Actividad.8.Reconocimiento.GPS.pdf)

**Comment by NoeliaGlez** [comment]
20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
